### ISSUE TITLE
Auto restart virtuoso/httpd after server reboot

### ISSUE THREAD

**Issue by frmichel** [issa-project/issa-pipeline#5]

**Comment by AnnaBobasheva** [comment]
By adding `--restart always` option to the virtuoso container run command we ensured that the container would restart upon Docker daemon's restart. 
[see here](https://github.com/issa-project/issa-pipeline/blob/main/environment/containers/virtuoso/run-virtuoso.sh)

**Comment by AnnaBobasheva** [comment]
Issue closed.
